import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { HabitsContext } from "./components/HabitsContext"
import { NextAuthProvider } from "./components/SessionProvider"
import { getServerSession } from "next-auth"
import { authOptions } from "./lib/auth"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body
        className={`${inter.className} theme-pak bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-zinc-700 via-zinc-900 to-black`} //"bg-gradient-to-t from-rose-200 via-rose-200 to-rose-300"
      >
        <NextAuthProvider session={session}>
          <HabitsContext>{children}</HabitsContext>
        </NextAuthProvider>
      </body>
    </html>
  )
}
